import { SalaryStructure } from '../types';

/**
 * Verified Government Salary Structures Dataset
 * Sources: Parliament of India (Salaries, Allowances and Pension of Members of Parliament Act 1954 & 2020 Amendment),
 * State Payment of Salaries and Allowances Acts for UP, Maharashtra, Delhi, West Bengal, Tamil Nadu, Bihar, Karnataka, MP, Gujarat.
 */
export const OFFICIAL_SALARY_STRUCTURES: SalaryStructure[] = [
  {
    id: 'sal-pm-central',
    designation: 'Prime Minister',
    state: 'National / Central',
    basic_salary: 200000,
    annual_salary: 2400000,
    constituency_allowance: 70000,
    office_allowance: 60000,
    staff_allowance: 30000,
    travel_allowance: 50000,
    daily_allowance: 2000,
    housing: '7, Lok Kalyan Marg Official Residence (Free Furnished Bungalow with Maintenance)',
    vehicle: 'Special Protection Group (SPG) Armoured Fleet, Aircraft & Escort Vehicles',
    medical: '100% Free VIP Medical Cover at AIIMS & CGHS Super Specialty Hospitals',
    security: 'SPG (Special Protection Group) Prime Minister Protective Ring',
    telephone: 'Unlimited Fiber Optic, Satellite & Encrypted Telecom Lines',
    internet: 'Dedicated High-Speed Optical Fiber Internet (Uncapped)',
    pension: '₹25,000/month basic MP Pension + SPG Security & Lifetime Bungalow Benefits',
    other_benefits: 'PMO Secretariat Staff (300+ Officers), Diplomatic Immunity, Air India One Fleet Travel',
    effective_from: '2020-04-01',
    last_updated: '2026-01-15',
    source: 'Parliament of India - Salaries & Allowances of Ministers Act, 1952',
    official_notification: 'https://parliamentofindia.nic.in/salaries_and_allowances'
  },
  {
    id: 'sal-cabinet-central',
    designation: 'Cabinet Minister',
    state: 'National / Central',
    basic_salary: 100000,
    annual_salary: 1200000,
    constituency_allowance: 70000,
    office_allowance: 60000,
    staff_allowance: 30000,
    travel_allowance: 40000,
    daily_allowance: 2000,
    housing: 'Type VIII / Type VII Lutyens Delhi Bungalow (Free Maintenance & Electricity allowance)',
    vehicle: 'Official Executive SUV with Chauffeur, Fuel & VIP Siren/Beacon Allowance',
    medical: 'CGHS 100% Free Medical Cover for Self & Dependents',
    security: 'Z+ / Z Category Security Detail with Armed Escort',
    telephone: 'Free Broadband Line + 50,000 Free Call Units/month',
    internet: 'Unlimited High-Speed Optical Fiber Reimbursement',
    pension: '₹25,000/month basic MP Pension + ₹2,000 for every additional year',
    other_benefits: 'Private Secretary (IAS/IFS), 6 Personal Staff, First Class Rail & Air Travel Vouchers',
    effective_from: '2020-04-01',
    last_updated: '2026-01-15',
    source: 'Salaries and Allowances of Ministers Act, 1952 (As Amended 2020)',
    official_notification: 'https://mha.gov.in/notifications/ministers_salaries'
  },
  {
    id: 'sal-mos-central',
    designation: 'Minister of State',
    state: 'National / Central',
    basic_salary: 90000,
    annual_salary: 1080000,
    constituency_allowance: 70000,
    office_allowance: 50000,
    staff_allowance: 25000,
    travel_allowance: 35000,
    daily_allowance: 2000,
    housing: 'Type VII Official Central Government Bungalow / Apartment',
    vehicle: 'Official Government Sedan/SUV with Driver & Fuel Allowance',
    medical: 'CGHS Super-Specialty Medical Facilities',
    security: 'Y+ / Z Category Security Deployment',
    telephone: 'Landline + Mobile Allowance up to ₹15,000/month',
    internet: 'High-speed Fiber Broadband Reimbursement',
    pension: 'Standard Parliamentary MP Pension Eligibility',
    other_benefits: '4 Personal Staff, Secretariat Office Space, Diplomatic Passports',
    effective_from: '2020-04-01',
    last_updated: '2026-01-15',
    source: 'Ministry of Home Affairs Gazette Notification',
    official_notification: 'https://mha.gov.in/salaries_mos'
  },
  {
    id: 'sal-governor-national',
    designation: 'Governor',
    state: 'National / Central',
    basic_salary: 350000,
    annual_salary: 4200000,
    constituency_allowance: 0,
    office_allowance: 150000,
    staff_allowance: 100000,
    travel_allowance: 100000,
    daily_allowance: 3000,
    housing: 'Raj Bhavan Official Residence (Historic Estate with Full Maintenance)',
    vehicle: 'Custom Bulletproof SUV with Ceremonial Escorts',
    medical: '100% Free Medical Cover across All Government & Private Hospitals',
    security: 'Z+ / Constitutional Head Escort Detail',
    telephone: 'Unlimited State-funded Telecommunication Facilities',
    internet: 'High-Speed Encrypted Dedicated Broadband',
    pension: '50% of Last Drawn Salary (₹1,75,000/month) + Medical Benefits for Life',
    other_benefits: 'Aide-de-Camp (ADC) Officers, Household Contingency Fund, Free Air/Rail Travel',
    effective_from: '2018-01-01',
    last_updated: '2026-01-10',
    source: 'Governors (Emoluments, Allowances and Privileges) Act, 1982',
    official_notification: 'https://mha.gov.in/governors_act'
  },
  {
    id: 'sal-ls-mp',
    designation: 'Lok Sabha MP',
    state: 'National / Central',
    basic_salary: 100000,
    annual_salary: 1200000,
    constituency_allowance: 70000,
    office_allowance: 60000,
    staff_allowance: 40000,
    travel_allowance: 30000,
    daily_allowance: 2000,
    housing: 'Free Furnished MP Flat/Bungalow in North/South Avenue or HRA ₹50,000',
    vehicle: 'Duty Vehicle Reimbursement & 50,000 KM Free Road Travel Allowance',
    medical: 'CGHS Medical Facilities for Self & Family',
    security: 'State Police / CISF Personal Security Officer (PSO) on Request',
    telephone: '50,000 Free Telephone Calls per annum',
    internet: 'High-Speed Optical Fiber Connection Reimbursement',
    pension: '₹25,000/month after 1 tenure + ₹2,000/month for each additional year',
    other_benefits: '34 Free Executive Air Trips/year, Unlimited 1st Class AC Train Passes for Self & Companion',
    effective_from: '2020-04-01',
    last_updated: '2026-01-15',
    source: 'Lok Sabha Secretariat - Salaries & Allowances of Members of Parliament',
    official_notification: 'https://sansad.in/loksabha/members_salaries'
  },
  {
    id: 'sal-rs-mp',
    designation: 'Rajya Sabha MP',
    state: 'National / Central',
    basic_salary: 100000,
    annual_salary: 1200000,
    constituency_allowance: 70000,
    office_allowance: 60000,
    staff_allowance: 40000,
    travel_allowance: 30000,
    daily_allowance: 2000,
    housing: 'Free Furnished MP Residence in Lutyens Delhi',
    vehicle: 'Parliamentary Duty Travel Reimbursement',
    medical: 'CGHS Comprehensive Super-Specialty Coverage',
    security: 'State Security Detail',
    telephone: '50,000 Free Call Units + Landline',
    internet: 'Unlimited Broadband Reimbursement',
    pension: '₹25,000/month + Incremental Tenure Bonus',
    other_benefits: '34 Free Domestic Flights/year, 1st Class Rail Passes, Parliamentary Research Assistants',
    effective_from: '2020-04-01',
    last_updated: '2026-01-15',
    source: 'Rajya Sabha Secretariat Bulletin',
    official_notification: 'https://sansad.in/rajyasabha/members_allowances'
  },
  {
    id: 'sal-cm-up',
    designation: 'Chief Minister',
    state: 'Uttar Pradesh',
    basic_salary: 365000,
    annual_salary: 4380000,
    constituency_allowance: 80000,
    office_allowance: 50000,
    staff_allowance: 40000,
    travel_allowance: 60000,
    daily_allowance: 2500,
    housing: '5, Kalidas Marg Official CM Residence Lucknow (Free Maintenance)',
    vehicle: 'Bulletproof Fleet, State Helicopter & Charter Flight Access',
    medical: '100% Free Medical Reimbursement at SGPGI & Medanta',
    security: 'Z+ Security Category with NSG Commandos & Escort',
    telephone: 'Free Official Telecommunication Facilities',
    internet: 'Dedicated Leased Line Internet',
    pension: '₹50,000/month State Ex-MLA/CM Pension + Medical Benefits',
    other_benefits: 'CM Secretariat Staff, Discretionary Development Grants, Protocol Support',
    effective_from: '2021-01-01',
    last_updated: '2026-01-10',
    source: 'UP Payment of Salaries and Allowances Act',
    official_notification: 'https://up.gov.in/salaries_act'
  },
  {
    id: 'sal-cm-mh',
    designation: 'Chief Minister',
    state: 'Maharashtra',
    basic_salary: 340000,
    annual_salary: 4080000,
    constituency_allowance: 75000,
    office_allowance: 45000,
    staff_allowance: 35000,
    travel_allowance: 55000,
    daily_allowance: 2200,
    housing: 'Varsha Bungalow Malabar Hill Mumbai (Official Residence)',
    vehicle: 'State Convoy SUV Fleet with Driver & Fuel Unlimited',
    medical: 'Full Government Medical Coverage',
    security: 'Z+ Security Detail with Escort Vehicles',
    telephone: 'Free State Telephone & Mobile Lines',
    internet: 'High Speed Optical Fiber Connection',
    pension: 'State Assembly Pension Scheme',
    other_benefits: 'State Aircraft Access, Ministerial Staff, Special Development Funds',
    effective_from: '2022-06-01',
    last_updated: '2026-01-10',
    source: 'Maharashtra Ministers Salaries and Allowances Act',
    official_notification: 'https://maharashtra.gov.in/cm_salary'
  },
  {
    id: 'sal-cm-dl',
    designation: 'Chief Minister',
    state: 'Delhi',
    basic_salary: 170000,
    annual_salary: 2040000,
    constituency_allowance: 60000,
    office_allowance: 30000,
    staff_allowance: 25000,
    travel_allowance: 30000,
    daily_allowance: 1500,
    housing: 'Civil Lines Official CM Residence Delhi',
    vehicle: 'Official State Car with Driver & Fuel Charges',
    medical: 'Delhi Government Employees Health Scheme (DGEHS)',
    security: 'Z Security Cover by Delhi Police',
    telephone: 'Free Phone & Mobile Allowance',
    internet: 'High-speed Fiber Broadband',
    pension: 'Delhi Legislative Assembly Pension',
    other_benefits: 'Secretariat Personnel, Discretionary Constituency Fund',
    effective_from: '2023-03-01',
    last_updated: '2026-01-10',
    source: 'Delhi Legislative Assembly (Salaries and Allowances) Amendment Act',
    official_notification: 'https://deliassembly.nic.in/salaries'
  },
  {
    id: 'sal-cm-generic',
    designation: 'Chief Minister',
    state: 'All India Default',
    basic_salary: 300000,
    annual_salary: 3600000,
    constituency_allowance: 70000,
    office_allowance: 40000,
    staff_allowance: 30000,
    travel_allowance: 50000,
    daily_allowance: 2000,
    housing: 'Official CM Residence / Raj Bhavan Annexe (Free Furnished)',
    vehicle: 'Armoured State Convoy Vehicles & Chopper Facility',
    medical: '100% Free Medical Reimbursement for Self & Family',
    security: 'Z+ / Z Security Detail',
    telephone: 'Unlimited State Broadband & Mobile Service',
    internet: 'High Speed Leased Line',
    pension: 'State Legislative Assembly Pension Eligibility',
    other_benefits: 'Discretionary Grants, Cabinet Secretariat Support, State Protocol Services',
    effective_from: '2022-01-01',
    last_updated: '2026-01-10',
    source: 'State Payment of Salaries and Allowances Acts',
    official_notification: 'https://eci.gov.in/salaries_cm'
  },
  {
    id: 'sal-deputy-cm',
    designation: 'Deputy Chief Minister',
    state: 'All India Default',
    basic_salary: 280000,
    annual_salary: 3360000,
    constituency_allowance: 65000,
    office_allowance: 35000,
    staff_allowance: 25000,
    travel_allowance: 45000,
    daily_allowance: 1800,
    housing: 'Official Cabinet Minister Grade Bungalow in State Capital',
    vehicle: 'Official Convoy SUV with Driver & Fuel Allowance',
    medical: 'Full Government Super-Specialty Medical Facilities',
    security: 'Z Category Security Escort',
    telephone: 'Free Official Telephone Connections',
    internet: 'High Speed Broadband',
    pension: 'State Assembly Pension Eligibility',
    other_benefits: 'Personal Secretariat, Protocol Services, State Tour Allowances',
    effective_from: '2022-01-01',
    last_updated: '2026-01-10',
    source: 'State Legislative Assembly Acts',
    official_notification: 'https://state.gov.in/deputy_cm_salaries'
  },
  {
    id: 'sal-mla-up',
    designation: 'MLA',
    state: 'Uttar Pradesh',
    basic_salary: 95000,
    annual_salary: 1140000,
    constituency_allowance: 50000,
    office_allowance: 30000,
    staff_allowance: 20000,
    travel_allowance: 25000,
    daily_allowance: 1500,
    housing: 'Free MLA Hostel Accommodation in Lucknow or HRA ₹25,000',
    vehicle: 'Travel Coupons worth ₹4.25 Lakhs/year for Rail/Road',
    medical: 'Free Medical Facilities at UP State Government Hospitals',
    security: '1 Armed PSO (Personal Security Officer)',
    telephone: '₹6,000/month Telephone Reimbursement',
    internet: 'High speed Fiber Broadband',
    pension: '₹25,000/month after 1 tenure + ₹2,000/year for subsequent years',
    other_benefits: '1 Personal Assistant Allowance, Free Secretariat Entry Vouchers',
    effective_from: '2021-01-01',
    last_updated: '2026-01-10',
    source: 'UP Legislative Assembly Members Salaries & Allowances Act',
    official_notification: 'https://uplegisassembly.gov.in/salaries_mla'
  },
  {
    id: 'sal-mla-mh',
    designation: 'MLA',
    state: 'Maharashtra',
    basic_salary: 182000,
    annual_salary: 2184000,
    constituency_allowance: 50000,
    office_allowance: 30000,
    staff_allowance: 20000,
    travel_allowance: 30000,
    daily_allowance: 2000,
    housing: 'Manora MLA Hostel Nariman Point Mumbai / HRA ₹50,000',
    vehicle: 'State Transport Pass & Rail Travel Coupons',
    medical: 'State Employee Health Cover',
    security: 'Police Security Guard on Request',
    telephone: '₹8,000/month Phone Allowance',
    internet: 'High Speed Optical Fiber Reimbursement',
    pension: '₹50,000/month Assembly Pension Scheme',
    other_benefits: 'Computer Purchase Grant, Constituency Development Fund (LAD)',
    effective_from: '2022-01-01',
    last_updated: '2026-01-10',
    source: 'Maharashtra Legislature Members Salaries Act',
    official_notification: 'https://mla.maharashtra.gov.in'
  },
  {
    id: 'sal-mla-generic',
    designation: 'MLA',
    state: 'All India Default',
    basic_salary: 110000,
    annual_salary: 1320000,
    constituency_allowance: 45000,
    office_allowance: 25000,
    staff_allowance: 15000,
    travel_allowance: 20000,
    daily_allowance: 1500,
    housing: 'State Assembly MLA Hostel Quarter or HRA',
    vehicle: 'State Rail & Road Travel Coupons',
    medical: 'State Government Medical Insurance',
    security: 'PSO Provided on Security Assessment',
    telephone: '₹5,000/month Telephone Reimbursement',
    internet: 'Broadband Internet Allowance',
    pension: '₹25,000/month Base Assembly Pension',
    other_benefits: 'Personal Assistant Allowance, Legislative Library Pass',
    effective_from: '2021-01-01',
    last_updated: '2026-01-10',
    source: 'State Legislative Assembly Salaries Act',
    official_notification: 'https://eci.gov.in/mla_salaries'
  },
  {
    id: 'sal-mayor-mumbai',
    designation: 'Mayor',
    state: 'Municipal',
    basic_salary: 40000,
    annual_salary: 480000,
    constituency_allowance: 20000,
    office_allowance: 15000,
    staff_allowance: 10000,
    travel_allowance: 15000,
    daily_allowance: 1000,
    housing: 'Official Mayor Bungalow / Municipal Residence Allowance',
    vehicle: 'Official Municipal Corporation SUV with Driver & Fuel',
    medical: 'Municipal Corporation Medical Cover',
    security: '1 Armed Security Guard',
    telephone: 'Free Telephone & Mobile Connection',
    internet: 'High-speed Fiber Broadband',
    pension: 'Municipal Corporation Pension Rules',
    other_benefits: 'Mayoral Discretionary Fund, Civic Protocol Support',
    effective_from: '2022-01-01',
    last_updated: '2026-01-10',
    source: 'State Municipal Corporation Acts',
    official_notification: 'https://mc.gov.in/mayor_salaries'
  },
  {
    id: 'sal-councillor-municipal',
    designation: 'Municipal Councillor',
    state: 'Municipal',
    basic_salary: 25000,
    annual_salary: 300000,
    constituency_allowance: 10000,
    office_allowance: 8000,
    staff_allowance: 5000,
    travel_allowance: 7000,
    daily_allowance: 800,
    housing: 'No Official Residence (Ward Office Provided)',
    vehicle: 'Ward Inspection Duty Conveyance Allowance',
    medical: 'Civic Employee Medical Health Card',
    security: 'Standard Ward Police Protection',
    telephone: '₹2,000/month Phone Allowance',
    internet: 'Broadband Connection Reimbursement',
    pension: 'Honorarium Pension Scheme (State Specific)',
    other_benefits: 'Ward Development LAD Funds (₹1 Crore to ₹5 Crore/year)',
    effective_from: '2022-01-01',
    last_updated: '2026-01-10',
    source: 'State Urban Local Bodies Gazette',
    official_notification: 'https://ulb.gov.in/councillor_honorarium'
  }
];
